[package]
name = "easy-paper"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Dawnfz-Lenfeng <https://github.com/Dawnfz-Lenfeng>"]
license = "MIT"
description = "A ready-to-use Typst template for Chinese papers"
repository = "https://github.com/Dawnfz-Lenfeng/easy-paper"
exclude = ["assets"]
keywords = ["chinese", "typst", "cjk", "中文"]
categories = ["report", "paper"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "assets/output-1.png"
